# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-13 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address1',
            name='area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='address1',
            name='district',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='address1',
            name='house',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='address1',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='address1',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address1',
            name='street',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
