# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-13 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg', '0002_auto_20191113_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('0', 'RAW'), ('1', 'FRESH'), ('2', 'OLD')], max_length=1)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('itime', models.DateTimeField(auto_now_add=True)),
                ('ftime', models.DateTimeField(blank=True)),
                ('landmark', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('dist', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(default='india', max_length=30)),
                ('pin', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('user', models.ManyToManyField(related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
