# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-13 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_remove_post_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
    ]
