# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_auto_20191114_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
