# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-15 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_auto_20191114_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ftime',
            new_name='finaltime',
        ),
    ]
